# Generated by Django 4.2.6 on 2023-11-21 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('website', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='RealCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('web_link', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('head_photo', models.ImageField(upload_to='')),
                ('email_address', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(max_length=10)),
                ('price', models.PositiveIntegerField(max_length=10)),
                ('value', models.PositiveIntegerField(max_length=10)),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='Spot.digitalcurrency')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve', to='Spot.spot')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentMethod', to='Spot.user')),
            ],
        ),
        migrations.CreateModel(
            name='PairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair', to='Spot.digitalcurrency')),
                ('pair_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair', to='Spot.realcurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Spot.digitalcurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='Spot.user')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('exchange_rate', models.PositiveIntegerField(max_length=10)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market', to='Spot.spot')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_rate', to='Spot.pairtype')),
            ],
        ),
        migrations.AddField(
            model_name='digitalcurrency',
            name='interest',
            field=models.ManyToManyField(blank=True, related_name='digital_currency', to='Spot.user'),
        ),
        migrations.CreateModel(
            name='CurrencyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('exchange_rate', models.PositiveIntegerField(max_length=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='Spot.digitalcurrency')),
            ],
        ),
    ]
