# Generated by Django 4.2.6 on 2023-11-21 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='last_name',
        ),
        migrations.AlterField(
            model_name='currencydetail',
            name='exchange_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='marketingrate',
            name='exchange_rate',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='balance',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='value',
            field=models.PositiveIntegerField(),
        ),
    ]
