# Generated by Django 4.2.6 on 2023-11-21 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Spot', '0002_rename_password_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='method',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='spot',
            name='score',
            field=models.IntegerField(default=5),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_info', to='Spot.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_info', to='Spot.user')),
            ],
        ),
    ]
