# Generated by Django 4.2.6 on 2023-11-21 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spot', '0004_rename_user_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='coins',
            field=models.IntegerField(default=100000000),
        ),
        migrations.AddField(
            model_name='spot',
            name='flat',
            field=models.ManyToManyField(blank=True, related_name='spot', to='Spot.realcurrency'),
        ),
        migrations.AddField(
            model_name='spot',
            name='liquidity',
            field=models.IntegerField(default=100000000),
        ),
        migrations.AddField(
            model_name='spot',
            name='markets',
            field=models.IntegerField(default=100000000),
        ),
        migrations.AddField(
            model_name='spot',
            name='volume',
            field=models.IntegerField(default=100000000),
        ),
        migrations.AddField(
            model_name='spot',
            name='weekly_visit',
            field=models.IntegerField(default=100000000),
        ),
    ]
