# Generated by Django 4.2.6 on 2023-11-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spot', '0005_spot_coins_spot_flat_spot_liquidity_spot_markets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserves',
            name='balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='reserves',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('user', 'spot')},
        ),
    ]
