# Generated by Django 4.2.6 on 2023-11-23 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Spot', '0006_alter_reserves_balance_alter_reserves_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reserves',
            new_name='Reserve',
        ),
    ]
