# Generated by Django 4.2.7 on 2023-11-26 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('head_photo', models.ImageField(upload_to='')),
                ('email_address', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DigitalCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField()),
                ('website', models.CharField(max_length=100)),
                ('describe', models.CharField(max_length=2000)),
                ('interest', models.ManyToManyField(blank=True, related_name='digital_currency', to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='RealCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('web_link', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('score', models.IntegerField(default=5)),
                ('volume', models.IntegerField(default=100000000)),
                ('liquidity', models.IntegerField(default=100000000)),
                ('weekly_visit', models.IntegerField(default=100000000)),
                ('markets', models.IntegerField(default=100000000)),
                ('coins', models.IntegerField(default=100000000)),
                ('flat', models.ManyToManyField(blank=True, related_name='spot', to='app.realcurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField()),
                ('price', models.FloatField()),
                ('value', models.FloatField()),
                ('currency_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_currency', to='app.digitalcurrency')),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserve_spot', to='app.spot')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(default='', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PaymentMethod', to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='PairType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair', to='app.digitalcurrency')),
                ('pair_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair', to='app.realcurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app.digitalcurrency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='MarketingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('exchange_rate', models.PositiveIntegerField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market', to='app.spot')),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_rate', to='app.pairtype')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('exchange_rate', models.PositiveIntegerField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='app.digitalcurrency')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_info', to='app.spot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_info', to='app.customer')),
            ],
            options={
                'unique_together': {('user', 'spot')},
            },
        ),
    ]
